InfuseAI/ArtiVC

cmd/docs.go, cmd/pull.go, cmd/version.go, internal/core/config.go, internal/core/utils.go, internal/core/utils_test.go, internal/repository/errors.go, internal/repository/repository.go, internal/repository/s3.go
=> chore: unified coding style.

go.mod, go.sum, internal/core/manager.go, internal/core/utils_test.go, internal/meter/meter.go, internal/repository/http.go, internal/repository/local.go, internal/repository/repository.go, internal/repository/s3.go
```
$ art init s3://art-vcs/datasets/foobarbar
$ art push
upload objects: (125/125), speed: 1.07MB/s
0 modified(M), 125 added(+), 0 deleted(-), 0 renamed(R)
create commit: c1ff40606ec9d01eb3d33bddfc049f672eab5d69
update ref: latest -> c1ff40606ec9d01eb3d33bddfc049f672eab5d69
```
=> Implement speed progress message

cmd/config.go, cmd/init.go, cmd/util_test.go, cmd/utils.go, internal/repository/local.go, internal/repository/local_test.go
When uploading a file to remote. It should not have partial content at the destination.
=> Local repo support atomic upload

internal/core/manager.go, internal/core/types.go
When download a file from repo, follow the steps
1. Download from remote to `.art/tmp/<random>`
2. `rm <dest>`
3. `mv .art/tmp/<random> <dest>`
=> Implement the atomic download

cmd/get.go, cmd/pull.go, internal/core/errors.go, internal/core/manager.go, internal/core/manager_test.go, internal/core/types.go
Remove these options from art pull 
```
art pull --merge
art pull --sync
```
Change to
```
art pull --delete
```
=> Remove the merge and sync mode

.github/workflows/docs-publish.yml
Signed-off-by: Wei-Chun, Chang <wcchang@infuseai.io>
Co-authored-by: popcorny <celu@infuseai.io>
=> add docs publish action

internal/core/manager.go
Reproducible Steps
```
cd /mnt/somepoint
art get s3://art-vcs/datasets/flowers/
```
`/mnt/somepoint` is on a device other than /tmp device.
It would get cross device link error.
=> Fit art get in non-root device would fail

internal/core/manager.go
Don't upload files for same content.
=> [Enhancement] same content upload

internal/repository/s3.go
When upload big files to s3, there is no progress updated.
=> Fix s3 upload without progress

cmd/get.go, cmd/pull.go, internal/core/config.go, internal/core/manager.go, internal/core/types.go
support partial download
```
art get -o output repo -- path/to/file1 path/to/file2 data/
art pull -- path/to/partia
art pull v0.1.0 -- path/to/partia ...
```
=> support partial download

docs/content/en/repositories/ssh.md, internal/core/manager.go, internal/repository/http.go, internal/repository/local.go, internal/repository/rclone.go, internal/repository/repo_integration_test.go, internal/repository/repository.go, internal/repository/s3.go, internal/repository/ssh.go, internal/repository/ssh_test.go
usage:
```
git init ssh://<host>/path/to/your/repository
```
The host should be configured by ssh config
=> Support SSH repository

internal/repository/ssh.go
SSH repository support atomic upload. That is, no partial result is stored in the repository.
=> SSH repository support atomic upload

internal/core/manager.go, internal/core/manager_test.go, internal/core/types.go, internal/core/utils.go
- Symbolic link is now supported
- The file permission mode is currently supported.
=> Support symbolic link and file permission mode

cmd/root.go, internal/core/manager.go, internal/log/log.go
Use `avc --debug <subcommand>` and the debug message will go to stderr
=> Add debug global flag

Makefile
example:
```sh
GO=go1.17 make build
```
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
=> feat(build): support test/build in multiple go version.

.github/workflows/ci.yml
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
=> feat(CI): support testing in multiple go version

cmd/clone.go, cmd/docs.go, cmd/init.go, cmd/utils.go, internal/core/manager.go, internal/core/manager_test.go, internal/core/utils_test.go, internal/repository/azureblob.go, internal/repository/meter.go, internal/repository/rclone.go, internal/repository/repo_integration_test.go, internal/repository/ssh.go
=> refactor: Error return value must be checked.

cmd/clone.go, cmd/config.go, cmd/diff.go, cmd/docs.go, cmd/get.go, cmd/init.go, cmd/list.go, cmd/log.go, cmd/pull.go, cmd/push.go, cmd/put.go, cmd/status.go, cmd/tag.go, cmd/version.go
=> refactor(error): remove unnecessary code.

cmd/util_test.go
Hi reviewers,
This is a minimal change for unit test.
Please let me know, If there is any problem 🙂
[ref](https://levelup.gitconnected.com/how-you-can-avoid-using-else-in-your-code-871197a1adbc)
Alex
=> nit: remove else block

cmd/clone.go, cmd/config.go, cmd/init.go, cmd/utils.go, internal/core/manager.go, internal/repository/repo_integration_test.go, internal/repository/repository.go, internal/repository/repository_test.go
Signed-off-by: Wei-Chun, Chang <wcchang@infuseai.io>
=> fix url parsing error in ssh backend

docs/content/en/_index.md, docs/static/custom.css
- adjust the position of the entry button
- adjust features' headline font size
Signed-off-by: Wei-Chun, Chang <wcchang@infuseai.io>
=> adjust the entry button and features' headline

docs/content/en/_index.md
Signed-off-by: Wei-Chun, Chang <wcchang@infuseai.io>
=> revise description

internal/core/manager.go
=> chore(manager): also check err is nil or not
